apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secret
  namespace: cattle-monitoring-system
type: Opaque
stringData:
  monitoring.yaml: |
    - job_name: 'eccosp-ecp'
      metrics_path: '/ECP_MODULE/actuator/prometheus'
      scheme: https
      scrape_interval: 5s
      basic_auth:
        username: 'admin'
        password: 'password'
      tls_config:
        insecure_skip_verify: true
      static_configs:
        - targets: ['eccosp-ecp-endpoint-ep1-local-svc.eccosp:8443']
    - job_name: 'eccosp-edx'
      metrics_path: '/actuator/prometheus'
      scheme: https
      scrape_interval: 5s
      basic_auth:
        username: 'admin'
        password: 'password'
      tls_config:
        insecure_skip_verify: true
      static_configs:
        - targets: ['eccosp-edx-toolbox-tb1-svc.eccosp:8443']
