dependencies:

- name: ecp-endpoint
  version: 4.12.0
  repository: file://./charts/ecp-endpoint
  condition: ecp-endpoint.enabled

- name: ecp-directory
  version: 4.12.0
  repository: file://./charts/ecp-directory
  condition: ecp-directory.enabled

- name: ecp-broker
  version: 4.12.0
  repository: file://./charts/ecp-broker
  condition: ecp-broker.enabled

- name: edx-catalogue
  version: 1.13.0
  repository: file://./charts/edx-catalogue
  condition: edx-catalogue.enabled

- name: edx-toolbox
  version: 1.13.0
  repository: file://./charts/edx-toolbox
  condition: edx-toolbox.enabled
